<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61520" started-at="2017-12-29T16:29:04Z" finished-at="2017-12-29T16:30:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61520" started-at="2017-12-29T16:29:04Z" finished-at="2017-12-29T16:30:06Z">
      <class name="com.proton.email.bot.core.tests.ProtonTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="setUp" is-config="true" duration-ms="6910" started-at="2017-12-29T18:29:04Z" finished-at="2017-12-29T18:29:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Click_on_Create_Account_TEST()[pri:0, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Click_on_Create_Account_TEST" duration-ms="2795" started-at="2017-12-29T18:29:11Z" finished-at="2017-12-29T18:29:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_on_Create_Account_TEST -->
        <test-method status="PASS" signature="Select_free_plan_TEST()[pri:1, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Select_free_plan_TEST" duration-ms="4304" started-at="2017-12-29T18:29:14Z" finished-at="2017-12-29T18:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Select_free_plan_TEST -->
        <test-method status="PASS" signature="Fill_form_details_and_create_dotCom_account_TEST()[pri:2, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Fill_form_details_and_create_dotCom_account_TEST" duration-ms="6939" started-at="2017-12-29T18:29:18Z" finished-at="2017-12-29T18:29:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fill_form_details_and_create_dotCom_account_TEST -->
        <test-method status="FAIL" signature="Confirm_Human_and_Verify_Email_TEST()[pri:3, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Confirm_Human_and_Verify_Email_TEST" duration-ms="14376" started-at="2017-12-29T18:29:25Z" finished-at="2017-12-29T18:29:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.proton.email.bot.core.tests.ProtonTests.Confirm_Human_and_Verify_Email_TEST(ProtonTests.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Confirm_Human_and_Verify_Email_TEST -->
        <test-method status="PASS" signature="Verify_Proton_MSG_Inside_Gmail_Inbox_TEST()[pri:4, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Verify_Proton_MSG_Inside_Gmail_Inbox_TEST" duration-ms="20984" started-at="2017-12-29T18:29:39Z" finished-at="2017-12-29T18:30:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Proton_MSG_Inside_Gmail_Inbox_TEST -->
        <test-method status="FAIL" signature="Grab_From_Thread_and_Retreive_BiggerKeyPass_TEST()[pri:5, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Grab_From_Thread_and_Retreive_BiggerKeyPass_TEST" duration-ms="5181" started-at="2017-12-29T18:30:00Z" finished-at="2017-12-29T18:30:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.proton.email.bot.core.tests.ProtonTests.Grab_From_Thread_and_Retreive_BiggerKeyPass_TEST(ProtonTests.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Grab_From_Thread_and_Retreive_BiggerKeyPass_TEST -->
      </class> <!-- com.proton.email.bot.core.tests.ProtonTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
